### ISSUE TITLE
Implement the space alien trading post

### ISSUE THREAD

**Issue by nukeop** [minexew/TempleOS#1]
Users have nowhere to make offerings at, a space alien trading post is urgently needed

**Comment by minexew** [comment]
I don't believe we should waste time on technical issues.

Setting up a proper Code Of Conduct is more important right now.

**Comment by nukeop** [comment]
Terry dies and the first thing that goes out the window is the space alien trading post...

**Comment by minexew** [comment]
The paypal has dried out, we gotta cut costs now
