### ISSUE TITLE
[Question] Is TempleOS free software?

### ISSUE THREAD

**Issue by ghbjklhv** [minexew/TempleOS#10]
**Question**: Aye, is TempleOS [free software](https://www.wikipedia.org/wiki/Free_software)? 

Also, I noticed the README stated HolyC as the C++ dialect, is that also all [free software](https://www.wikipedia.org/wiki/Free_software)?

**Comment by kernel-pan-ic** [comment]
I believe Terry Davis (who is now deceased) made all his code relating to TempleOS and HolyC in the public domain. The website [https://templeos.org/](https://templeos.org/) states: 

> All content related to Terry A. Davis, TempleOS, J Operating System, SparrowOS, or LoseThos should be considered public domain. 

So, yes, TempleOS and the HolyC language and compiler are free/libre software, and additionally, public domain.

**Comment by minexew** [comment]
Indeed, everything is public domain, including the entirety of this repo.
