### ISSUE TITLE
The language bar says that this is C++

### ISSUE THREAD

**Issue by DanteFalzone0** [minexew/TempleOS#11]
I know that GitHub recognizes HolyC because I've seen it on other projects. Why does the linguist identify this as being mostly C++?

**Comment by mcejp** [comment]
Hint: https://github.com/minexew/TempleOS/search?l=c%2B%2B

**Comment by shit-ware** [comment]
Heresy.

**Comment by minexew** [comment]
By the time the last commit was pushed, GitHub did not yet recognize HolyC. Therefore the language bar only picked up on some C++ files and HolyC headers with ".HH" extension which is also classified as C++.

**Comment by DanteFalzone0** [comment]
Would the language checker read it over again if a new commit was pushed? It could just be a tiny text file or something, not saying that we should actually change the code

**Comment by shit-ware** [comment]
My only guess is to redo the repo.

**Comment by minexew** [comment]
This is now resolved, by the way.
