### ISSUE TITLE
Why is there C++ code?

### ISSUE THREAD

**Issue by dontknowhy** [minexew/TempleOS#16]
why C++???

**Comment by TheTechRobo** [comment]
It's actually HolyC, Terry A Davis made that dialect himself.

Unless you mean the Compiler, in which case that's probably because C/++ was the de facto standard back then and almost any programmer when he started knew C/++.

**Comment by vexy** [comment]
> It's actually HolyC, Terry A Davis made that dialect himself.

Speaking of which, is there any reference to `HolyC` like docs or readme ?

**Comment by TheTechRobo** [comment]
There's a lot of docs in TempleOS itself.

**Comment by erober416** [comment]
The only C++ is TOSZ.cpp which is just a utility for converting media from templeos to something normal for Linux. It was probably just for him to share some of those media with the internet
