### ISSUE TITLE
include historic releases of j, sparrow os, losethos ?

### ISSUE THREAD

**Issue by kbilsted** [minexew/TempleOS#6]
I think it would be great to also include in the commit history the files from the predecessors of templeos. From the video demos from around 2010 and 2012 it those generations of the OS looks very very similar to Temple. By getting the source in Git, we can actually determine the rate of change after 2012

**Comment by minexew** [comment]
Is there a reasonably complete archive of those older releases?

**Comment by kbilsted** [comment]
It's failing on fuse. I can pr an Iso if you want to try extracting

**Comment by kbilsted** [comment]
Where can I find older versions of the extractor

**Comment by minexew** [comment]
https://github.com/minexew/TempleOS/commit/0e5871772481f7a176a0f78532374bc78e24f372 this is the last commit with the ISO9660 extractor

**Comment by kbilsted** [comment]
Are we talking about the same thing here ? I thought the extractor was python script. That commit contains no python.

**Comment by minexew** [comment]
It sure does.

**Comment by minexew** [comment]
There is one more step that needs to be done: `apply isoparser.patch`

But anyways, check out https://github.com/minexew/TempleOS/commits/archive

**Comment by minexew** [comment]
Nightly versions up to 11/2017 are now included as well.

**Comment by kbilsted** [comment]
great stuff. What is your source of the ISO's you extract?

**Comment by slx7R4GDZM** [comment]
Here's some historic releases.
https://uploadfiles.io/xiom3
I found them on archive.org, didn't do TempleOS.org since the site was huge and wasn't sure if this would be useful.

**Comment by trapexit** [comment]
https://archive.org/details/TerryADavis_TempleOS_Archive
https://archive.org/details/TempleOS_ISO_Archive

**Comment by minexew** [comment]
https://archive.org/details/TempleOS_ISO_Archive is the one I used.

**Comment by minexew** [comment]
@slx7R4GDZM That's a nice collection, but what are those releases of LoseThos from 2011 to 2014? TempleOS was a thing by then

**Comment by kbilsted** [comment]
they are really close. Looking at the diff from sparrow to templeos many files simply changed folder and suffix. It'd be fun to do a better diff than vanilla git diff to identify when most of the OS was done. Demos from https://archive.org/download/TerryADavis_TempleOS_Archive/videos/2010/  2010 shows almost the same as modern temple videos

**Comment by slx7R4GDZM** [comment]
@minexew 
>but what are those releases of LoseThos from 2011 to 2014?

2011-2012 don't surprise me since archive.org shows that LoseThos V8.04 is first listed on the main page of the site around September 2nd 2012.
After that though I'm not really sure what's going on.
